name: AkalaboChat
<<<<<<< HEAD
main: net.tuyapin.alc.AkalaboChat
version: 1.7.2.30
description: Japanese Convert Plugin
website: http://tuyapin.net/
author: tuyapin
commands:
  alc:
    description: AkalaboChat functions
    usage: /<command>

=======
author: tuyapin
main: net.tuyapin.alc.AkalaboChat
version: 1.5.2.27
commands:
  alc:
    description: All Start Commands for AkalaboChat.
    usage: /alc <arg1> [prm1]...
>>>>>>> 172
permission: 
  alc.add:
  alc.del:
  alc.help: