name: AkalaboChat
author: tuyapin
main: net.tuyapin.alc.AkalaboChat
version: 1.5.2.27
commands:
  alc:
    description: All Start Commands for AkalaboChat.
    usage: /alc <arg1> [prm1]...
permission: 
  alc.add:
  alc.del:
  alc.help: