name: AkalaboChat
main: net.tuyapin.alc.AkalaboChat
version: 1.7.2.30
description: Japanese Convert Plugin
author: tuyapin
commands:
  alc:
    description: AkalaboChat functions
    usage: /<command>

permission: 
  alc.add:
  alc.del:
  alc.help:
